version: '3.8'

services:
  dev.nginx:
    image: myapp.dev.nginx
    container_name: dev.nginx
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'
    volumes:
      - ./config/nginx.dev.conf:/etc/nginx/nginx.conf:ro
