# Use postgres/example user/password credentials

version: '3.8'
services:
  dev.postgres:
    image: postgres:15.3-alpine
    container_name: dev.postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db_dev:/var/lib/postgresql/data/pgdata
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    # ports:
    #   - 5432:5432

  dev.adminer:
    image: adminer
    container_name: dev.adminer
    restart: always
    ports:
      - 8000:8080

  dev.pgadmin:
    image: dpage/pgadmin4
    container_name: dev.pgadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: fakemail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
