version: '3.8'

services:
  dev.mongo:
    image: mongo:6.0
    container_name: dev.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./db_dev:/data/db
